# Generated by Django 2.1.7 on 2019-05-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to='firstapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='project_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentor', models.BooleanField(default=False)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.project')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.person')),
            ],
        ),
    ]
